### ISSUE TITLE
[Bug] 与新版AdvancedSeasons不兼容

### ISSUE THREAD

**Issue by mon030** [Xiao-MoMi/Custom-Fishing#38]
AdvancedSeasons版本1.4.1
CustomFishing 版本2.2.15
ItemsAdder版本 4.0.2-alpha-test-3 仅托管CustomFishing 的材质包
服务端版本 paper-1.21-126

<details><summary>Details</summary>
<p>

[16:11:56 INFO]: [CustomFishing] Enabling CustomFishing v2.2.15
[16:11:57 INFO]: [CustomFishing] ItemsAdder hooked!
[16:11:57 INFO]: [CustomFishing] EcoJobs hooked!
[16:11:57 INFO]: [CustomFishing] EcoSkills hooked!
[16:11:57 INFO]: [CustomFishing] AdvancedSeasons hooked!
[16:11:57 ERROR]: Error occurred while enabling CustomFishing v2.2.15 (Is it up to date?)
java.lang.NoClassDefFoundError: net/advancedplugins/seasons/api/AdvancedSeasonsAPI
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.integration.season.AdvancedSeasonsProvider.<init>(AdvancedSeasonsProvider.java:31) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.integration.BukkitIntegrationManager.load(BukkitIntegrationManager.java:129) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.integration.BukkitIntegrationManager.<init>(BukkitIntegrationManager.java:63) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.BukkitCustomFishingPluginImpl.enable(BukkitCustomFishingPluginImpl.java:133) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.BukkitBootstrap.onEnable(BukkitBootstrap.java:35) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-126-7e44684]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-126-7e44684]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-126-7e44684]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-126-7e44684]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.advancedplugins.seasons.api.AdvancedSeasonsAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 17 more
[16:11:57 INFO]: [CustomFishing] Disabling CustomFishing v2.2.15
[16:11:57 ERROR]: Error occurred while disabling CustomFishing v2.2.15
java.lang.NullPointerException: Cannot invoke "net.momirealms.customfishing.api.storage.DataStorageProvider.updateManyPlayersData(java.util.Collection, boolean)" because the return value of "net.momirealms.customfishing.api.storage.StorageManager.getDataSource()" is null
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.bag.BukkitBagManager.disable(BukkitBagManager.java:93) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.BukkitCustomFishingPluginImpl.disable(BukkitCustomFishingPluginImpl.java:210) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at CustomFishing-2.2.15-566a0dc6.jar/net.momirealms.customfishing.bukkit.BukkitBootstrap.onDisable(BukkitBootstrap.java:40) ~[CustomFishing-2.2.15-566a0dc6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-126-7e44684]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-126-7e44684]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-126-7e44684]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-126-7e44684]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-126-7e44684]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-126-7e44684]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-126-7e44684]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:11:57 INFO]: [AdvancedSeasons] Enabling AdvancedSeasons v1.4.1

</p>
</details> 
完整log:https://mclo.gs/7f2Egek

**Comment by Xiao-MoMi** [comment]
感谢反馈，前几天已经修过了，但是还未发布。
