### ISSUE TITLE
Failed to start when using the Paper 1.21.1 core

### ISSUE THREAD

**Issue by microvencn** [Xiao-MoMi/Custom-Fishing#39]
Thanks to the author for his work and amazing results. I would like to report a problem with the plugin not starting. 

Paper core: 1.21.1 Build#131
```
[21:54:27] [Server thread/ERROR]: Error occurred while enabling CustomFishing v2.2.31 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R2/inventory/CraftContainer
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at CustomFishing-2.2.31.jar/net.momirealms.customfishing.bukkit.nms.SparrowHeart$SingletonHolder.getHeart(SparrowHeart.java:63) ~[CustomFishing-2.2.31.jar:?]
	at CustomFishing-2.2.31.jar/net.momirealms.customfishing.bukkit.nms.SparrowHeart$SingletonHolder.<clinit>(SparrowHeart.java:42) ~[CustomFishing-2.2.31.jar:?]
	at CustomFishing-2.2.31.jar/net.momirealms.customfishing.bukkit.nms.SparrowHeart.getInstance(SparrowHeart.java:34) ~[CustomFishing-2.2.31.jar:?]
	at CustomFishing-2.2.31.jar/net.momirealms.customfishing.bukkit.BukkitCustomFishingPluginImpl.enable(BukkitCustomFishingPluginImpl.java:117) ~[CustomFishing-2.2.31.jar:?]
	at CustomFishing-2.2.31.jar/net.momirealms.customfishing.bukkit.BukkitBootstrap.onEnable(BukkitBootstrap.java:35) ~[CustomFishing-2.2.31.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R2.inventory.CraftContainer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
```
I wonder if this is because of my poor use of the plugin or some inevitable oversight. Thanks!
:)

**Comment by Xiao-MoMi** [comment]
Hello, from your log, I found that there seems to be a problem with the paper version you are using. Did you download the server from the paper official website?

**Comment by microvencn** [comment]
> It's a problem with the 1.21.3 support draft. Will fix that soon

Thanks for the reply. Good luck with your development.
