### ISSUE TITLE
An error occurred when the player joined the server

### ISSUE THREAD

**Issue by microvencn** [Xiao-MoMi/Custom-Fishing#41]
```
[[CustomFishing] Thread customfishing-worker-1 threw an uncaught exception
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at CustomFishing-2.2.32.jar/net.momirealms.customfishing.api.storage.data.PlayerData$Builder.build(PlayerData.java:125) ~[CustomFishing-2.2.32.jar:?]
        at CustomFishing-2.2.32.jar/net.momirealms.customfishing.bukkit.storage.method.file.YAMLProvider.getPlayerData(YAMLProvider.java:81) ~[CustomFishing-2.2.32.jar:?]
        at CustomFishing-2.2.32.jar/net.momirealms.customfishing.bukkit.storage.BukkitStorageManager.lambda$waitLock$9(BukkitStorageManager.java:308) ~[CustomFishing-2.2.32.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```
When I want to use the /sellfish command, the following message appears:
![image](https://github.com/user-attachments/assets/0cd1a40c-cd1d-44f9-9020-1277d4f4c8a7)
If I delete the data/ directory, this will be fixed for now. But when I join the server again, it happens again.

Server core: Paper 1.21.1 Build#131
Plugin version: [2.2.32](https://github.com/Xiao-MoMi/Custom-Fishing/releases/tag/2.2.32)
If you need more information, please let me know. :)

**Comment by Xiao-MoMi** [comment]
Fixed in latest commit
